print("\nGit y gitHub CLI - Opciones:")
print("1. Establecer el directorio del trabajo")
print("2. Crear un nuevo repositorio")
print("3. Crear una nueva rama")
print("4. Cambiar de rama")
print("5. Mostrar ficheros pendientes de hacer commit")
print("6. Hacer commit (+add)")
print("\nGit y gitHub CLI - Opciones:")
print("\nGit y gitHub CLI - Opciones:")
print("\nGit y gitHub CLI - Opciones:")
print("\nGit y gitHub CLI - Opciones:")
print("\nGit y gitHub CLI - Opciones:")
